main/urls.py
"""Urls module for the main app."""

from django.conf import settings
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.ProjectsListView.as_view(), name="projects"),
    path("funding/", views.FundingListView.as_view(), name="funding"),
    path("capacities/", views.CapacitiesListView.as_view(), name="capacities"),
    path(
        "funding/create/",
        views.FundingCreateView.as_view(),
        name="funding_create",
    ),
    path(
        "projects/create/",
        views.ProjectCreateView.as_view(),
        name="project_create",
    ),
    path(
        "funding/<slug:pk>/update",
        views.FundingUpdateView.as_view(),
        name="funding_update",
    ),
    path(
        "projects/<slug:pk>/", views.ProjectDetailView.as_view(), name="project_detail"
    ),
    path(
        "projects/<slug:pk>/update",
        views.ProjectUpdateView.as_view(),
        name="project_update",
    ),
    path(
        "projects/<slug:project_pk>/phase/<slug:pk>",
        views.ProjectPhaseDetailView.as_view(),
        name="project_phase_detail",
    ),
    path(
        "project-phase/create/",
        views.ProjectPhaseCreateView.as_view(),
        name="project_phase_create",
    ),
    path(
        "projects/<slug:project_pk>/phase/<slug:pk>/delete/",
        views.ProjectPhaseDeleteView.as_view(),
        name="project_phase_delete",
    ),
    path(
        "projects/<slug:project_pk>/phase/<slug:pk>/update/",
        views.ProjectPhaseUpdateView.as_view(),
        name="project_phase_update",
    ),
    path(
        "funding/<slug:pk>/", views.FundingDetailView.as_view(), name="funding_detail"
    ),
    path(
        "capacity_planning/",
        views.CapacityPlanningView.as_view(),
        name="capacity_planning",
    ),
    path(
        "cost_recovery/",
        views.CostRecoveryView.as_view(),
        name="cost_recovery",
    ),
]

if settings.DEBUG and not settings.USE_OIDC:
    urlpatterns += [
        path("register/", views.RegistrationView.as_view(), name="auth_register"),
    ]

procat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

if settings.USE_OIDC:
    urlpatterns += [
        path("oidc/", include("mozilla_django_oidc.urls")),
    ]

if settings.DEBUG:
    urlpatterns += [
        path("auth/", include("django.contrib.auth.urls")),
    ]

main/forms.py
"""Forms needed by ProCAT."""

from typing import ClassVar

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils import timezone

from . import models


class CustomUserCreationForm(UserCreationForm):  # type: ignore [type-arg]
    """Form to create users with the custom User model.

    TODO: This is a placeholder for development. When SSO is implemented, this won't be
    needed since available users will be retrieved automatically.
    """

    class Meta:
        """Meta class for the form."""

        model = get_user_model()
        fields = ("username", "email")


class CostRecoveryForm(forms.Form):
    """Form to use in the Cost Recovery view."""

    _MONTHS = (
        (1, "January"),
        (2, "February"),
        (3, "March"),
        (4, "April"),
        (5, "May"),
        (6, "June"),
        (7, "July"),
        (8, "August"),
        (9, "September"),
        (10, "October"),
        (11, "November"),
        (12, "December"),
    )
    current_year = timezone.now().year
    _YEARS = ((year, str(year)) for year in range(current_year, current_year - 5, -1))

    month = forms.TypedChoiceField(
        choices=_MONTHS,
        label="Month",
        coerce=int,
        initial=timezone.now().month,
        help_text="Month for which to generate the charges report.",
    )
    year = forms.TypedChoiceField(
        choices=_YEARS,
        label="Year",
        coerce=int,
        help_text="Year for which to generate the charges report.",
    )


class FundingForm(forms.ModelForm):  # type: ignore [type-arg]
    """Form to create and edit funding instances."""

    class Meta:
        """Meta class for the form."""

        model = models.Funding
        fields = "__all__"
        widgets: ClassVar = {
            "expiry_date": forms.DateInput(format=("%Y-%m-%d"), attrs={"type": "date"}),
        }


class ProjectForm(forms.ModelForm):  # type: ignore [type-arg]
    """Form to create and edit Project instances."""

    class Meta:
        """Meta class for the form."""

        model = models.Project
        exclude = ("notifications_effort", "notifications_weeks")
        widgets: ClassVar = {
            "start_date": forms.DateInput(format=("%Y-%m-%d"), attrs={"type": "date"}),
            "end_date": forms.DateInput(format=("%Y-%m-%d"), attrs={"type": "date"}),
        }


class ProjectPhaseForm(forms.ModelForm):  # type: ignore [type-arg]
    """Form to create and edit Project Phase instances."""

    class Meta:
        """Meta class for the form."""

        model = models.ProjectPhase
        fields = "__all__"
        widgets: ClassVar = {
            "start_date": forms.DateInput(format=("%Y-%m-%d"), attrs={"type": "date"}),
            "end_date": forms.DateInput(format=("%Y-%m-%d"), attrs={"type": "date"}),
        }

main/views.py
"""Views for the main app."""

from typing import Any

import bokeh
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import Form, ModelForm
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    FormView,
    ListView,
    TemplateView,
    UpdateView,
)
from django_filters.views import FilterView
from django_tables2 import RequestConfig, SingleTableMixin

from . import forms, models, plots, report, tables


class RegistrationView(CreateView):  # type: ignore [type-arg]
    """View to register new users.

    TODO: This is a placeholder for development. When SSO is implemented, this won't be
    needed since available users will be retrieved automatically.
    """

    form_class = forms.CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/register.html"


class ProjectsListView(LoginRequiredMixin, FilterView):
    """View to display the list of projects split in five pre-filtered tables."""

    model = models.Project
    template_name = "main/projects.html"
    filterset_fields = ("nature", "department", "status", "charging")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # type: ignore
        """Add multiple pre-filtered tables to the context."""
        context = super().get_context_data(**kwargs)

        base_qs = self.get_queryset()

        buckets = [
            ("Active", {"status": "Active"}, "active-"),
            ("Confirmed", {"status": "Confirmed"}, "confirmed-"),
            ("Tentative", {"status": "Tentative"}, "tentative-"),
            ("Finished", {"status": "Finished"}, "finished-"),
            ("Not done", {"status": "Not done"}, "not-done-"),
        ]

        created_tables: list[tuple[str, tables.ProjectTable]] = []
        for title, filt, prefix in buckets:
            qs = base_qs.filter(**filt)
            tbl = tables.ProjectTable(qs, prefix=prefix)
            RequestConfig(self.request).configure(tbl)
            created_tables.append((title, tbl))

        context["tables"] = created_tables
        return context


class FundingListView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    SingleTableMixin,
    ListView,  # type: ignore [type-arg]
):
    """View to display the funding list for all projects."""

    permission_required = "main.view_funding"
    raise_exception = False

    model = models.Funding
    table_class = tables.FundingTable
    template_name = "main/funding.html"


class CapacitiesListView(
    LoginRequiredMixin, PermissionRequiredMixin, SingleTableMixin, FilterView
):
    """View to display the list of capacities."""

    permission_required = "main.view_capacity"
    raise_exception = False

    model = models.Capacity
    table_class = tables.CapacityTable
    template_name = "main/capacities.html"
    filterset_fields = ("user",)


class CustomBaseDetailView(LoginRequiredMixin, UpdateView):  # type: ignore [type-arg]
    """Detail view based on a read-only form view.

    While there is a generic Detail View, it is not rendered nicely easily as the
    bootstrap theme needs to be applied on a field by field basis. So we use a form view
    instead, which can easily be styled, and make the form read only.
    """

    fields = "__all__"

    def get_form(self, form_class: Any | None = None) -> ModelForm:  # type: ignore
        """Customize form to make it read-only.

        Args:
            form_class: The form class to use, if any.

        Return:
            A form associated to the model.
        """
        form = super().get_form(form_class)

        for field in form.fields.keys():
            form.fields[field].widget.attrs["disabled"] = True
            form.fields[field].widget.attrs["readonly"] = True

        return form


class ProjectDetailView(PermissionRequiredMixin, CustomBaseDetailView):
    """View to view details of a project."""

    model = models.Project
    template_name = "main/project_detail.html"
    permission_required = "main.view_project"
    raise_exception = False
    fields = None  # type: ignore
    form_class = forms.ProjectForm

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # type: ignore
        """Add project name and funding table to the context.

        A custom query is used with the funding table, so only the funding for the
        current project is displayed.
        """
        context = super().get_context_data(**kwargs)
        context["project_name"] = self.get_object().name
        # get funding info for the current project
        funding_source = self.get_object().funding_source.all()
        funding_table = tables.FundingTable(funding_source)
        project_phase = models.ProjectPhase.objects.filter(
            project__name=self.get_object().name
        )
        phase_table = tables.ProjectPhaseTable(project_phase)
        # enables the table to be sorted by column headings
        RequestConfig(self.request).configure(funding_table)
        RequestConfig(self.request).configure(phase_table)

        context["funding_table"] = funding_table
        context["phase_table"] = phase_table
        return context


class FundingDetailView(PermissionRequiredMixin, CustomBaseDetailView):
    """View to view details of project funding."""

    model = models.Funding
    template_name = "main/funding_detail.html"
    permission_required = "main.view_funding"
    raise_exception = False

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # type: ignore
        """Add funding name to the context, so it is easy to retrieve."""
        context = super().get_context_data(**kwargs)
        funding = self.get_object()
        context["funding_name"] = str(funding)

        # Monthly charges table for this funding
        charges_qs = models.MonthlyCharge.objects.filter(funding=funding).order_by(
            "-date"
        )
        charges_table = tables.MonthlyChargeTable(charges_qs)
        RequestConfig(self.request).configure(charges_table)
        context["monthly_charges_table"] = charges_table

        return context


class CapacityPlanningView(LoginRequiredMixin, TemplateView):
    """View that renders the Capacity Planning page."""

    template_name = "main/capacity_planning.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # type: ignore
        """Add HTML components and Bokeh version to the context."""
        context = super().get_context_data(**kwargs)
        layout = plots.create_capacity_planning_layout()
        context.update(plots.html_components_from_plot(layout))
        context["bokeh_version"] = bokeh.__version__
        return context


class CostRecoveryView(LoginRequiredMixin, FormView):  # type: ignore [type-arg]
    """View that renders the Cost Recovery page."""

    template_name = "main/cost_recovery.html"
    form_class = forms.CostRecoveryForm

    def form_valid(self, form: Form) -> HttpResponse:
        """Generate csv using the dates provided in the form."""
        month = form.cleaned_data["month"]
        year = form.cleaned_data["year"]
        response = report.create_charges_report_for_download(month, year)
        return response

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # type: ignore
        """Add HTML components and Bokeh version to the context."""
        context = super().get_context_data(**kwargs)
        layout = plots.create_cost_recovery_layout()
        context.update(plots.html_components_from_plot(layout))
        context["bokeh_version"] = bokeh.__version__
        return context


class FundingCreateView(PermissionRequiredMixin, CreateView):  # type: ignore [type-arg]
    """View to create a new funding."""

    permission_required = "main.create_funding"
    raise_exception = False

    model = models.Funding
    form_class = forms.FundingForm
    template_name = "main/funding_form.html"
    success_url = reverse_lazy("main:funding")


class ProjectCreateView(PermissionRequiredMixin, CreateView):  # type: ignore [type-arg]
    """View to create a new project."""

    permission_required = "main.create_project"
    raise_exception = False

    model = models.Project
    form_class = forms.ProjectForm
    template_name = "main/project_form.html"
    success_url = reverse_lazy("main:projects")


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):  # type: ignore [type-arg]
    """Update view based on a form from the Project model."""

    model = models.Project
    template_name = "main/project_update.html"
    permission_required = "main.change_project"
    raise_exception = False
    form_class = forms.ProjectForm

    def get_success_url(self):  # type: ignore [no-untyped-def]
        """Django magic function to obtain a dynamic success URL."""
        return reverse_lazy("main:project_detail", kwargs={"pk": self.object.pk})


class ProjectPhaseCreateView(PermissionRequiredMixin, CreateView):  # type: ignore [type-arg]
    """View to create a new project phase."""

    permission_required = "main.create_project_phase"
    raise_exception = False

    model = models.ProjectPhase
    form_class = forms.ProjectPhaseForm
    template_name = "main/project_phase_form.html"
    success_url = reverse_lazy("main:projects")


class ProjectPhaseDetailView(PermissionRequiredMixin, CustomBaseDetailView):
    """View to view details of a project."""

    model = models.ProjectPhase
    template_name = "main/project_phase_detail.html"
    permission_required = "main.view_project_phase"
    raise_exception = False

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # type: ignore
        """Add project name and funding table to the context.

        A custom query is used with the funding table, so only the funding for the
        current project is displayed.
        """
        context = super().get_context_data(**kwargs)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      {% block title %}
        ProCAT
      {% endblock title %}
    </title>
    <meta name="description" content="ProCAT">
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extra_css %}
    {% endblock extra_css %}
    {% block extra_js %}
    {% endblock extra_js %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    {% include "main/navbar.html" %}
    <div class="container-fluid py-3">
      <!-- Changed to container-fluid for full width -->
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

main/templates/main/base_create.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

  <style>p {text-align: justify;}</style>

  {% block create %}
  {% endblock create %}

  <form method="post">
    {% csrf_token %}
    <div class="text-left">{% bootstrap_button button_type="submit" content="🖫 Save" %}</div>
    <p>&nbsp;</p>
    {% bootstrap_form form layout='horizontal' %}
  </form>

{% endblock content %}

main/templates/main/base_update.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

  <style>p {text-align: justify;}</style>

  {% block update %}
  {% endblock update %}

  <form method="post">
    {% csrf_token %}
    <div class="text-left">{% bootstrap_button button_type="submit" content="✎ Update" %}</div>
    <p>&nbsp;</p>
    {% bootstrap_form form layout='horizontal' %}
  </form>

{% endblock content %}

main/templates/main/capacities.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% load django_tables2 %}
{% block content %}
  <h2>Capacities</h2>
  <!-- Shortcut to access the capacities list url -->
  {% url 'main:capacities' as capacities %}
  <!-- Filter -->
  <form action="" method="get" class="form form-inline">
    <div class="row">
      <div class="col-lg-5">{% bootstrap_form filter.form layout='horizontal' %}</div>
      <div class="col-lg-5">
        {% bootstrap_button 'Filter' %}
        {% bootstrap_button 'Clear' button_type="link" button_class="btn-success" href=capacities %}
      </div>
    </div>
  </form>
  <!-- Table -->
  {% render_table table %}
{% endblock content %}

main/templates/main/cost_recovery.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% block content %}

  <style>p {text-align: justify;}</style>

  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-{{ bokeh_version }}.min.js"></script>
  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-{{ bokeh_version }}.min.js"></script>
  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-{{ bokeh_version }}.min.js"></script>
  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-gl-{{ bokeh_version }}.min.js"></script>
  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-mathjax-{{ bokeh_version }}.min.js"></script>

  <h2>Cost recovery</h2>

  <br>

  <!-- Page description and form -->

  <div class="container-fluid">
    <div class="row align-items-top gx-5">
      <div class="col-md-6">
        <h6>Description</h6>
        <p>
          This page displays information related to past charges. Here, you can download
          the charges report (in csv format) for past months and visualise cost recovery
          data. The first plot, '<i>Team capacity and project charging over time</i>',
          displays the average capacity for project work and the fraction of capacity
          that was recovered (based on Clockify data). The second plot, '<i>Total monthly
          charges</i>', shows aggregated monthly charges for each month.
        </p>
      </div>
      <div class="col-md-6">
        <form method="post">
          <h6>Download charges report</h6>
          {% csrf_token %}
          {% bootstrap_form form layout="horizontal" %}
          {% if user.is_superuser %}
            {% bootstrap_button button_type="submit" content="Download CSV" %}
          {% endif %}
        </form>
      </div>
    </div>

    <br>

    <!-- Bokeh plots -->

    <h6>Cost recovery plots</h6>

    {{ script | safe }}
    {{ div | safe }}

  </div>

{% endblock content %}

main/templates/main/funding.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% load django_tables2 %}
{% block content %}
  <h2>Funding</h2>
  {% if perms.main.create_funding %}
    <a class="btn btn-primary" href="{% url 'main:funding_create' %}">+ Create Funding</a>
  {% endif %}
  {% render_table table %}
{% endblock content %}

main/templates/main/navbar.html
<!--Navbar-->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:projects' %}">
      <h1>ProCAT</h1>
    </a>
    <ul class="navbar-nav me-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:capacity_planning' %}">Capacity planning</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:cost_recovery' %}">Cost recovery</a>
        </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <!-- We welcome the user and include a few useful links -->
        <li class="nav-item">
          <a class="nav-link">Welcome: {{ user.username }}</a>
        </li>
        {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin site</a>
          </li>
        {% endif %}
        <li class="nav-item">
          {% if use_OIDC %}
            <form method="post" action="{% url 'oidc_logout' %}">
              {% csrf_token %}
              <input class="nav-link logout-button" type="submit" value="Logout" />
            </form>
          {% else %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <input class="nav-link logout-button" type="submit" value="Logout" />
            </form>
          {% endif %}
        </li>
      {% else %}
        <!-- Otherwise we just show options to login -->
        <li>
          {% if use_OIDC %}
            <a class="nav-link" href="{% url 'oidc_authentication_init' %}">Login</a>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:auth_register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
          {% endif %}
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

main/templates/main/project_create.html
{% extends "main/base_create.html" %}

{% block create %}
  <h2>Create a Project</h2>

  <p>
    Fill in the form below to create a new project and add it to the database.
    *Note: Only superusers can create new projects.*
  </p>
{% endblock create %}

main/templates/main/project_detail.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% load django_tables2 %}
{% block content %}
  <h2>{{ project_name }}</h2>
  {% if perms.main.create_project %}
    <a class="btn btn-primary" href="{{ request.path }}update">✎ Update Project</a>
  {% endif %}
  <!-- Object details -->
  <div class="row">
    <div class="col">
      <p>&nbsp;</p>
      {% bootstrap_form form layout='horizontal' %}
    </div>
  </div>
  <!-- Phases table -->
  <h2>Project Phases:</h2>
  {% if perms.main.create_project_phase %}
    <a class="btn btn-primary" href="{% url 'main:project_phase_create' %}">+ Create Project Phase</a>
  {% endif %}
  {% render_table phase_table %}
  <!-- Funding table -->
  <h2>Funding sources:</h2>
  <div class="text-start">
    <a href="{% url 'main:funding_create' %}" class="btn btn-primary">+ Create Funding</a>
  </div>
  {% render_table funding_table %}
{% endblock content %}

main/templates/main/project_form.html
{% extends "main/base_create.html" %}

{% block create %}
  <h2>Create a Project</h2>

  <p>Fill in the form below to create a new project and add it to the database.</p>
{% endblock create %}

main/templates/main/project_phase_delete.html
{% extends "main/base_delete.html" %}

{% block create %}
  <h2>Delete Project Phase</h2>

  <p>
    Are you sure you want to delete the project phase from {{ object.start_date }} to {{ object.end_date }} for project {{ object.project.name }}?
  </p>

{% endblock create %}

main/templates/main/project_phases.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% load django_tables2 %}
{% block content %}
  <h2>Project Phases</h2>
  {% if perms.main.create_project_phase %}
    <a class="btn btn-primary" href="{% url 'main:project_phase_create' %}">+ Create Project Phase</a>
  {% endif %}
  {% for title, table in tables %}
    <h3 class="mt-4">{{ title }}</h3>
    {% render_table table %}
  {% endfor %}
{% endblock content %}

main/templates/main/project_update.html
{% extends "main/base_update.html" %}

{% block update %}
  <h2>Update a Project</h2>

  <p>Edit fields in the form below to update a project and save it to the database.</p>
{% endblock update %}

main/templates/main/projects.html
{% extends "main/base.html" %}
{% load django_bootstrap5 %}
{% load django_tables2 %}
{% block content %}
  <h2>Projects</h2>
  {% if perms.main.create_project %}
    <a class="btn btn-primary" href="{% url 'main:project_create' %}">+ Create Project</a>
  {% endif %}
  {% for title, table in tables %}
    <h3 class="mt-4">{{ title }}</h3>
    {% render_table table %}
  {% endfor %}
{% endblock content %}